In [ ]:
# Section 1 - Data Understanding

# install libraries if not already available
!pip install pandas numpy matplotlib seaborn --quiet

In [ ]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

print("Libraries imported successfully")

Libraries imported successfully

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving app_events.csv to app_events.csv
Saving complaints.csv to complaints.csv
Saving customers.csv to customers.csv
Saving data_dictionary.csv to data_dictionary.csv
Saving deliveries.csv to deliveries.csv
Saving drivers.csv to drivers.csv
Saving hubs.csv to hubs.csv
Saving incidents.csv to incidents.csv
Saving orders.csv to orders.csv
Saving vehicles.csv to vehicles.csv

In [ ]:


## Cell 4 – Load datasets
app_event = pd.read_csv("app_events.csv")
complaint = pd.read_csv("complaints.csv")
customer = pd.read_csv("customers.csv")
data_dictionary = pd.read_csv("data_dictionary.csv")
drivers = pd.read_csv("drivers.csv")
hubs = pd.read_csv("hubs.csv")
incidents = pd.read_csv("incidents.csv")
orders = pd.read_csv("orders.csv")
vehicle = pd.read_csv("vehicles.csv")

print("All datasets loaded successfully")

All datasets loaded successfully

In [ ]:
print("APP EVENT")
display(app_event.head())

print("COMPLAINT")
display(complaint.head())

print("CUSTOMER")
display(customer.head())

print("DRIVERS")
display(drivers.head())

print("ORDERS")
display(orders.head())

print("VEHICLE")
display(vehicle.head())

APP EVENT

,event_id,customer_id,order_id,event_timestamp,event_type,session_id,device_type,zone_context,api_latency_ms,success_flag
0,AE00001,C0488,NaN,2024-08-09 03:25:00,eta_refresh,S19847,Android,north,301,1
1,AE00002,C0595,O00950,2024-02-13 22:29:00,search_route,S32766,Android,SOUTH,60,1
2,AE00003,C0494,O00170,2025-08-11 09:29:00,chat_opened,S99516,iOS,Airport,1118,1
3,AE00004,C0407,O00756,2025-08-23 17:38:00,eta_refresh,S41236,iOS,CENTRAL,442,1
4,AE00005,C0506,NaN,2024-05-29 10:33:00,search_route,S12030,iOS,north,60,1

COMPLAINT

,complaint_id,customer_id,order_id,complaint_type,channel,severity,created_at,status,resolution_days,compensation_amount
0,CP0001,C0464,O00814,AppIssue,App,High,2025-03-30 02:36:00,Open,11,23.99
1,CP0002,C0056,O00628,MissedPickup,Phone,Medium,2024-11-07 10:05:00,Open,4,21.64
2,CP0003,C0469,O00384,Delay,Chatbot,High,2024-01-02 15:47:00,Open,16,26.41
3,CP0004,C0631,O00406,Delay,App,Medium,2025-01-14 13:07:00,AwaitingCustomer,7,23.44
4,CP0005,C0535,O00154,Delay,Email,Medium,2024-08-31 05:56:00,Resolved,1,16.18

CUSTOMER

,customer_id,age,home_zone,customer_type,signup_date,loyalty_score,app_engagement_score,preferred_channel,account_status
0,C0001,26,North,SME,2024-11-27 04:25:00,44.9,69.2,App,Active
1,C0002,61,AIRPORT,Consumer,2025-10-28 01:04:00,55.4,66.6,App,Active
2,C0003,66,East,Consumer,2025-07-02 03:23:00,75.9,33.8,NaN,Active
3,C0004,75,CENTRAL,Consumer,2025-08-19 01:58:00,32.5,33.0,App,Active
4,C0005,26,Riverside,Consumer,2025-06-03 06:02:00,55.9,100.0,Web,Active

DRIVERS

,driver_id,base_zone,employment_type,years_experience,training_score,driver_rating,shift_preference,active_flag
0,D001,AIRPORT,FullTime,8,67.8,3.54,Morning,1
1,D002,Central,FullTime,4,42.4,3.94,Evening,1
2,D003,AIRPORT,FullTime,11,96.5,5.00,Evening,1
3,D004,Airport,PartTime,13,88.9,4.75,Morning,1
4,D005,north,FullTime,3,69.7,4.14,Morning,1

ORDERS

,order_id,customer_id,service_type,order_created_at,promised_window_hours,pickup_zone,dropoff_zone,priority_level,order_value,booking_channel,special_handling_flag
0,O00001,C0292,Passenger,2024-08-20 14:43:00,6,Airport,South,Medium,126.65,App,0
1,O00002,C0459,Passenger,2024-05-14 22:16:00,24,North,AIRPORT,Low,109.30,App,0
2,O00003,C0161,Passenger,2025-09-02 14:37:00,4,West,AIRPORT,High,33.50,Phone,0
3,O00004,C0520,Parcel,2025-01-11 17:15:00,2,RiverSide,North,Medium,10.04,App,1
4,O00005,C0558,Retail,2025-02-17 19:32:00,12,Riverside,SOUTH,Low,125.58,Phone,0

VEHICLE

,vehicle_id,vehicle_type,assigned_zone,commission_date,battery_health_pct,odometer_km,maintenance_status,telematics_version
0,V001,EV,North,2024-12-28 23:48:00,71.8,56928,Active,v2.2
1,V002,EV,AIRPORT,2024-04-21 16:14:00,67.9,159368,InRepair,v2.2
2,V003,CargoVan,north,2025-11-24 23:59:00,91.7,219359,Active,v2.1
3,V004,Hybrid,RiverSide,2024-06-07 13:21:00,NaN,36310,Active,v2.2
4,V005,CargoVan,West,2025-11-15 11:08:00,58.6,146638,Active,v2.2

Cell 6 – Dataset shape (rows and columns)

In [ ]:
datasets = {
    "app_event": app_event,
    "complaint": complaint,
    "customer": customer,
    "drivers": drivers,
    "hubs": hubs,
    "incidents": incidents,
    "orders": orders,
    "vehicle": vehicle
}

for name, df in datasets.items():
    print(f"{name} shape:", df.shape)

app_event shape: (640, 10)
complaint shape: (320, 10)
customer shape: (650, 9)
drivers shape: (170, 8)
hubs shape: (8, 5)
incidents shape: (280, 7)
orders shape: (1250, 11)
vehicle shape: (120, 8)

Cell 7 – Column names

In [ ]:
for name, df in datasets.items():
    print(f"\n{name} columns:")
    print(df.columns.tolist())

app_event columns:
['event_id', 'customer_id', 'order_id', 'event_timestamp', 'event_type', 'session_id', 'device_type', 'zone_context', 'api_latency_ms', 'success_flag']

complaint columns:
['complaint_id', 'customer_id', 'order_id', 'complaint_type', 'channel', 'severity', 'created_at', 'status', 'resolution_days', 'compensation_amount']

customer columns:
['customer_id', 'age', 'home_zone', 'customer_type', 'signup_date', 'loyalty_score', 'app_engagement_score', 'preferred_channel', 'account_status']

drivers columns:
['driver_id', 'base_zone', 'employment_type', 'years_experience', 'training_score', 'driver_rating', 'shift_preference', 'active_flag']

hubs columns:
['hub_id', 'hub_name', 'zone', 'hub_type', 'capacity_score']

incidents columns:
['incident_id', 'delivery_id', 'incident_type', 'reported_at', 'severity', 'resolution_status', 'resolved_hours']

orders columns:
['order_id', 'customer_id', 'service_type', 'order_created_at', 'promised_window_hours', 'pickup_zone', 'dropoff_zone', 'priority_level', 'order_value', 'booking_channel', 'special_handling_flag']

vehicle columns:
['vehicle_id', 'vehicle_type', 'assigned_zone', 'commission_date', 'battery_health_pct', 'odometer_km', 'maintenance_status', 'telematics_version']

Cell 8 – Data types

In [ ]:
for name, df in datasets.items():
    print(f"\n{name} data types:")
    print(df.dtypes)

app_event data types:
event_id           object
customer_id        object
order_id           object
event_timestamp    object
event_type         object
session_id         object
device_type        object
zone_context       object
api_latency_ms      int64
success_flag        int64
dtype: object

complaint data types:
complaint_id            object
customer_id             object
order_id                object
complaint_type          object
channel                 object
severity                object
created_at              object
status                  object
resolution_days          int64
compensation_amount    float64
dtype: object

customer data types:
customer_id              object
age                       int64
home_zone                object
customer_type            object
signup_date              object
loyalty_score           float64
app_engagement_score    float64
preferred_channel        object
account_status           object
dtype: object

drivers data types:
driver_id            object
base_zone            object
employment_type      object
years_experience      int64
training_score      float64
driver_rating       float64
shift_preference     object
active_flag           int64
dtype: object

hubs data types:
hub_id            object
hub_name          object
zone              object
hub_type          object
capacity_score     int64
dtype: object

incidents data types:
incident_id           object
delivery_id           object
incident_type         object
reported_at           object
severity              object
resolution_status     object
resolved_hours       float64
dtype: object

orders data types:
order_id                  object
customer_id               object
service_type              object
order_created_at          object
promised_window_hours      int64
pickup_zone               object
dropoff_zone              object
priority_level            object
order_value              float64
booking_channel           object
special_handling_flag      int64
dtype: object

vehicle data types:
vehicle_id             object
vehicle_type           object
assigned_zone          object
commission_date        object
battery_health_pct    float64
odometer_km             int64
maintenance_status     object
telematics_version     object
dtype: object

Cell 9 – Missing values

In [ ]:
missing_values = {}

for name, df in datasets.items():
    missing = df.isnull().sum()
    missing_values[name] = missing
    print(f"\nMissing values in {name}")
    print(missing[missing > 0])

Missing values in app_event
order_id    144
dtype: int64

Missing values in complaint
compensation_amount    16
dtype: int64

Missing values in customer
loyalty_score        20
preferred_channel    13
dtype: int64

Missing values in drivers
training_score    7
dtype: int64

Missing values in hubs
Series([], dtype: int64)

Missing values in incidents
resolved_hours    17
dtype: int64

Missing values in orders
booking_channel    25
dtype: int64

Missing values in vehicle
battery_health_pct    4
dtype: int64

Cell 10 – Duplicate records

In [ ]:
for name, df in datasets.items():
    duplicates = df.duplicated().sum()
    print(f"{name} duplicate rows: {duplicates}")

app_event duplicate rows: 0
complaint duplicate rows: 0
customer duplicate rows: 0
drivers duplicate rows: 0
hubs duplicate rows: 0
incidents duplicate rows: 0
orders duplicate rows: 0
vehicle duplicate rows: 0

Cell 11 – Summary statistics (numerical columns)

In [ ]:
for name, df in datasets.items():
    print(f"\nSummary statistics for {name}")
    display(df.describe())

Summary statistics for app_event

       api_latency_ms  success_flag
count      640.000000    640.000000
mean       465.667188      0.940625
std        271.634155      0.236510
min         60.000000      0.000000
25%        278.750000      1.000000
50%        432.500000      1.000000
75%        609.000000      1.000000
max       1701.000000      1.000000

Summary statistics for complaint

       resolution_days  compensation_amount
count       320.000000           304.000000
mean          7.928125            20.257204
std           5.214324            15.002195
min           1.000000             0.000000
25%           3.750000             8.822500
50%           7.000000            18.405000
75%          11.000000            29.145000
max          25.000000            61.850000

Summary statistics for customer

              age  loyalty_score  app_engagement_score
count  650.000000     630.000000            650.000000
mean    46.738462      59.690635             58.132308
std     17.449179      16.124674             18.918154
min     18.000000      13.100000              1.000000
25%     32.000000      49.000000             45.375000
50%     46.000000      59.600000             59.000000
75%     62.000000      70.450000             72.000000
max     78.000000      99.000000            100.000000

Summary statistics for drivers

       years_experience  training_score  driver_rating  active_flag
count        170.000000      163.000000     170.000000   170.000000
mean           8.223529       74.914724       4.171706     0.947059
std            4.114850       11.213827       0.406301     0.224578
min            1.000000       40.600000       3.150000     0.000000
25%            5.000000       68.550000       3.905000     1.000000
50%            8.500000       75.200000       4.175000     1.000000
75%           11.750000       82.750000       4.477500     1.000000
max           15.000000       99.000000       5.000000     1.000000

Summary statistics for hubs

       capacity_score
count        8.000000
mean        73.875000
std          8.408117
min         63.000000
25%         68.250000
50%         72.500000
75%         79.000000
max         88.000000

Summary statistics for incidents

       resolved_hours
count      263.000000
mean        12.011407
std          7.751258
min          0.000000
25%          5.150000
50%         11.500000
75%         17.950000
max         41.700000

Summary statistics for orders

       promised_window_hours  order_value  special_handling_flag
count            1250.000000  1250.000000            1250.000000
mean                7.621600    91.050520               0.190400
std                 7.057015    60.917783               0.392774
min                 1.000000     2.040000               0.000000
25%                 4.000000    47.915000               0.000000
50%                 6.000000    76.530000               0.000000
75%                12.000000   121.097500               0.000000
max                24.000000   510.060000               1.000000

Summary statistics for vehicle

       battery_health_pct    odometer_km
count          116.000000     120.000000
mean            76.785345  115739.466667
std             12.698985   58256.963436
min             42.000000   15138.000000
25%             68.200000   67927.500000
50%             78.050000  112293.000000
75%             85.775000  160087.500000
max            100.000000  219359.000000

Cell 11 – Summary statistics (numerical columns)

In [ ]:
for name, df in datasets.items():
    print(f"\nSummary statistics for {name}")
    display(df.describe())

Summary statistics for app_event

       api_latency_ms  success_flag
count      640.000000    640.000000
mean       465.667188      0.940625
std        271.634155      0.236510
min         60.000000      0.000000
25%        278.750000      1.000000
50%        432.500000      1.000000
75%        609.000000      1.000000
max       1701.000000      1.000000

Summary statistics for complaint

       resolution_days  compensation_amount
count       320.000000           304.000000
mean          7.928125            20.257204
std           5.214324            15.002195
min           1.000000             0.000000
25%           3.750000             8.822500
50%           7.000000            18.405000
75%          11.000000            29.145000
max          25.000000            61.850000

Summary statistics for customer

              age  loyalty_score  app_engagement_score
count  650.000000     630.000000            650.000000
mean    46.738462      59.690635             58.132308
std     17.449179      16.124674             18.918154
min     18.000000      13.100000              1.000000
25%     32.000000      49.000000             45.375000
50%     46.000000      59.600000             59.000000
75%     62.000000      70.450000             72.000000
max     78.000000      99.000000            100.000000

Summary statistics for drivers

       years_experience  training_score  driver_rating  active_flag
count        170.000000      163.000000     170.000000   170.000000
mean           8.223529       74.914724       4.171706     0.947059
std            4.114850       11.213827       0.406301     0.224578
min            1.000000       40.600000       3.150000     0.000000
25%            5.000000       68.550000       3.905000     1.000000
50%            8.500000       75.200000       4.175000     1.000000
75%           11.750000       82.750000       4.477500     1.000000
max           15.000000       99.000000       5.000000     1.000000

Summary statistics for hubs

       capacity_score
count        8.000000
mean        73.875000
std          8.408117
min         63.000000
25%         68.250000
50%         72.500000
75%         79.000000
max         88.000000

Summary statistics for incidents

       resolved_hours
count      263.000000
mean        12.011407
std          7.751258
min          0.000000
25%          5.150000
50%         11.500000
75%         17.950000
max         41.700000

Summary statistics for orders

       promised_window_hours  order_value  special_handling_flag
count            1250.000000  1250.000000            1250.000000
mean                7.621600    91.050520               0.190400
std                 7.057015    60.917783               0.392774
min                 1.000000     2.040000               0.000000
25%                 4.000000    47.915000               0.000000
50%                 6.000000    76.530000               0.000000
75%                12.000000   121.097500               0.000000
max                24.000000   510.060000               1.000000

Summary statistics for vehicle

       battery_health_pct    odometer_km
count          116.000000     120.000000
mean            76.785345  115739.466667
std             12.698985   58256.963436
min             42.000000   15138.000000
25%             68.200000   67927.500000
50%             78.050000  112293.000000
75%             85.775000  160087.500000
max            100.000000  219359.000000

Cell 12 – Unique values for categorical columns

In [ ]:
for name, df in datasets.items():
    print(f"\n{name} categorical values")

    categorical_cols = df.select_dtypes(include='object').columns

    for col in categorical_cols:
        unique_vals = df[col].nunique()
        print(f"{col}: {unique_vals} unique values")

app_event categorical values
event_id: 640 unique values
customer_id: 412 unique values
order_id: 413 unique values
event_timestamp: 640 unique values
event_type: 8 unique values
session_id: 637 unique values
device_type: 3 unique values
zone_context: 16 unique values

complaint categorical values
complaint_id: 320 unique values
customer_id: 233 unique values
order_id: 285 unique values
complaint_type: 7 unique values
channel: 4 unique values
severity: 3 unique values
created_at: 317 unique values
status: 4 unique values

customer categorical values
customer_id: 650 unique values
home_zone: 16 unique values
customer_type: 3 unique values
signup_date: 650 unique values
preferred_channel: 4 unique values
account_status: 3 unique values

drivers categorical values
driver_id: 170 unique values
base_zone: 16 unique values
employment_type: 3 unique values
shift_preference: 4 unique values

hubs categorical values
hub_id: 8 unique values
hub_name: 8 unique values
zone: 7 unique values
hub_type: 4 unique values

incidents categorical values
incident_id: 280 unique values
delivery_id: 248 unique values
incident_type: 8 unique values
reported_at: 280 unique values
severity: 4 unique values
resolution_status: 4 unique values

orders categorical values
order_id: 1250 unique values
customer_id: 568 unique values
service_type: 5 unique values
order_created_at: 1248 unique values
pickup_zone: 16 unique values
dropoff_zone: 16 unique values
priority_level: 4 unique values
booking_channel: 4 unique values

vehicle categorical values
vehicle_id: 120 unique values
vehicle_type: 4 unique values
assigned_zone: 16 unique values
commission_date: 120 unique values
maintenance_status: 3 unique values
telematics_version: 4 unique values

Cell 13 – Inspect zone inconsistencies

In [ ]:
print("Zones in customers:")
print(customer['home_zone'].unique())

print("\nDriver base zones:")
print(drivers['base_zone'].unique())

print("\nHub zones:")
print(hubs['zone'].unique())

print("\nOrder pickup zones:")
print(orders['pickup_zone'].unique())

print("\nVehicle assigned zones:")
print(vehicle['assigned_zone'].unique())

Zones in customers:
['North' 'AIRPORT' 'East' 'CENTRAL' 'Riverside' 'WEST' 'north' 'South'
 'West' 'Ctr' 'Airport' 'EAST' 'SOUTH' 'RiverSide' 'NORTH' 'Central']

Driver base zones:
['AIRPORT' 'Central' 'Airport' 'north' 'CENTRAL' 'North' 'SOUTH' 'West'
 'East' 'NORTH' 'EAST' 'WEST' 'Riverside' 'South' 'RiverSide' 'Ctr']

Hub zones:
['North' 'South' 'East' 'West' 'Central' 'Airport' 'Riverside']

Order pickup zones:
['Airport' 'North' 'West' 'RiverSide' 'Riverside' 'CENTRAL' 'NORTH'
 'South' 'WEST' 'East' 'Ctr' 'SOUTH' 'Central' 'AIRPORT' 'north' 'EAST']

Vehicle assigned zones:
['North' 'AIRPORT' 'north' 'RiverSide' 'West' 'Central' 'South' 'NORTH'
 'Riverside' 'SOUTH' 'WEST' 'Airport' 'CENTRAL' 'EAST' 'East' 'Ctr']

Cell 14 – Date columns check

In [ ]:
date_columns = {
    "app_event": "event_timestamp",
    "complaint": "created_at",
    "customer": "signup_date",
    "incidents": "reported_at",
    "orders": "order_created_at",
    "vehicle": "commission_date"
}

for dataset, col in date_columns.items():
    print(f"\nChecking {dataset} date column")

    df = datasets.get(dataset)

    if col in df.columns:
        print(df[col].head())

Checking app_event date column
0    2024-08-09 03:25:00
1    2024-02-13 22:29:00
2    2025-08-11 09:29:00
3    2025-08-23 17:38:00
4    2024-05-29 10:33:00
Name: event_timestamp, dtype: object

Checking complaint date column
0    2025-03-30 02:36:00
1    2024-11-07 10:05:00
2    2024-01-02 15:47:00
3    2025-01-14 13:07:00
4    2024-08-31 05:56:00
Name: created_at, dtype: object

Checking customer date column
0    2024-11-27 04:25:00
1    2025-10-28 01:04:00
2    2025-07-02 03:23:00
3    2025-08-19 01:58:00
4    2025-06-03 06:02:00
Name: signup_date, dtype: object

Checking incidents date column
0    2024-03-11 23:46:00
1    2024-02-21 10:56:00
2    2025-04-17 23:22:00
3    2025-02-09 00:16:00
4    2025-01-04 02:49:00
Name: reported_at, dtype: object

Checking orders date column
0    2024-08-20 14:43:00
1    2024-05-14 22:16:00
2    2025-09-02 14:37:00
3    2025-01-11 17:15:00
4    2025-02-17 19:32:00
Name: order_created_at, dtype: object

Checking vehicle date column
0    2024-12-28 23:48:00
1    2024-04-21 16:14:00
2    2025-11-24 23:59:00
3    2024-06-07 13:21:00
4    2025-11-15 11:08:00
Name: commission_date, dtype: object

Cell 15 – Basic observations print

In [ ]:
print("""
Initial Observations:

1. Some datasets contain missing values.
2. Zone names have inconsistent formatting (North, north, NORTH).
3. Date columns need conversion to datetime format.
4. Some datasets contain categorical variables.
5. Some records do not have linked order_id.
6. Semi-structured behaviour seen in app events and incidents.
""")

Initial Observations:

1. Some datasets contain missing values.
2. Zone names have inconsistent formatting (North, north, NORTH).
3. Date columns need conversion to datetime format.
4. Some datasets contain categorical variables.
5. Some records do not have linked order_id.
6. Semi-structured behaviour seen in app events and incidents.